# Generated by Django 3.1.7 on 2021-03-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_kushovna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kushovna',
            new_name='Hovno',
        ),
    ]
