# Generated by Django 3.1.7 on 2021-03-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210307_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hovno',
            new_name='Hovno2',
        ),
    ]
