# Generated by Django 3.1.7 on 2021-03-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210307_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hovno2',
        ),
    ]
